services:
  # PHP Backend (Yii2) - только PHP-FPM
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_HOST=db
      - DB_NAME=yii2app
      - DB_USER=root
      - DB_PASSWORD=password
    expose:
      - 9000
    depends_on:
      - db

  # Nuxt3 Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_URL=http://nginx/api

  # Nginx (основной веб-сервер)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend
      - frontend

  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=yii2app
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: